### PR TITLE
Switched to AsyncKeyedLock library

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by KuraiAndras** [comment]
@MarkCiliaVincenti so how does this improve things? Would this reduce threadpool pressure? I am not really familiary with AsyncKeyedLock

**Comment by MarkCiliaVincenti** [comment]
The existing code is leaving items permanently in `_locks`. It also creates a heavy(ish) `SemaphoreSlim` object every time. This library cleans up and uses pooled `SemaphoreSlim` objects so it will have less allocations and won't leak memory.

**Comment by KuraiAndras** [comment]
Before merging this, could you add your library to this project? https://github.com/xoofx/UnityNuGet Right now I use this mostly inside Unity, and this library is added to xoofx's nuget project, so adding a new dependency to the project needs to be present there also.
Als I need to update the github pipeline so outside prs can run the CI pipeline

**Comment by MarkCiliaVincenti** [comment]
> Before merging this, could you add your library to this project? https://github.com/xoofx/UnityNuGet Right now I use this mostly inside Unity, and this library is added to xoofx's nuget project, so adding a new dependency to the project needs to be present there also. Als I need to update the github pipeline so outside prs can run the CI pipeline

I don't see a suitable need for UnityNuGet to make use of AsyncKeyedLock though. Can you point me exactly where it could be used? Nobody is going to accept a PR adding a library that's unused in their code.

**Comment by KuraiAndras** [comment]
the registry.json file contains the list of nuget pakcages availiable in the registry. AsyncKeyLock needs to be in the registry in order to be used by projects

**Comment by MarkCiliaVincenti** [comment]
So you mean something like this? https://github.com/xoofx/UnityNuGet/pull/167

**Comment by KuraiAndras** [comment]
Yes, almost, the published version needs to be the lowest version which supports .net standard 2.0 (1.0.0 of your package), and I think the `System.Threading.Tasks.Extensions` does not need to be modified.
The registry.json file specifies the lowest supported version of packages, and the server serves all versions above that. The `System.Threading.Tasks.Extensions` package is not listed, because the Unity Editor serves that DLL explicitly, so its not listed by the registry

**Comment by MarkCiliaVincenti** [comment]
Ah ok,

Check now.

Regards,

Mark Cilia Vincenti

**Comment by KuraiAndras** [comment]
yeah, this looks good, thanks

**Comment by KuraiAndras** [comment]
Thank you for this, I will create a new release later today

**Pull request merged**
